Repository Sports-day/sports-day-form, pull requests merged in 2024-04, with the labels that each got.

#12 formのログイン画面構築
  app/layout.tsx
  app/login/page.tsx
  components/PolicyButton.tsx
  components/auth/LoginButton.tsx
  components/palette.tsx
  components/theme/index.tsx
  package-lock.json
  yarn.lock
Labels: Type: new feature

#18 ヘッダーとフッターの追加
  app/form/page.tsx
  components/Footer.tsx
  components/Header.tsx
Labels: Type: new feature

#21 Fix Color Theme
  app/form/page.tsx
  app/layout.tsx
  app/login/page.tsx
  components/Footer.tsx
  components/Header.tsx
  components/PolicyButton.tsx
  components/auth/LoginButton.tsx
  components/palette.tsx
  components/theme/color.tsx
Labels: Type: new feature

#22 TeamTag モデル実装
  src/models/TeamTagModel.ts
  src/repositories/TeamTagRepository.ts
Labels: Type: new feature

#23 Add list display
  app/form/page.tsx
  app/layout.tsx
  app/list/page.tsx
  app/page.tsx
  components/AddTeam.tsx
  components/AthleteChip.tsx
  components/DeleteTeam.tsx
  components/Footer.tsx
  components/Header.tsx
  components/PolicyButton.tsx
  components/ProfileCard.tsx
  components/SportList.tsx
  components/SportTeams.tsx
  components/TeamChip.tsx
  components/TeamDetail.tsx
  components/TeamList.tsx
  components/UserData.tsx
  components/UserTable.tsx
  components/auth/LoginButton.tsx
  components/theme/color.tsx
  components/theme/index.tsx
  middleware.ts
  package.json
  src/models/TeamModel.ts
  yarn.lock
Labels: Type: new feature

#24 MultiSelectのキーとしてユーザーIDを使用するように変更
  components/TeamChip.tsx
Labels: Priority: high, Type: improvement

#25 認証エンドポイント変更による諸変更
  app/api/auth/callback/route.ts
Labels: Type: improvement

#26 Dockerfileの追加
  .github/workflows/docker-publish.yml
  Dockerfile
Labels: Type: new feature

#28 Nodeのバージョン更新
  Dockerfile
Labels: Type: new feature

#29 Alertの配置の修正
  app/page.tsx
Labels: Type: improvement

#33 FooterのButton表示設定
  components/BackButton.tsx
  components/ConfirmButton.tsx
  components/Footer.tsx
Labels: Type: new feature

#35 一定時間でページリフレッシュする機能
  app/page.tsx
  components/autoPageRefresh.tsx
Labels: Type: improvement, Type: new feature

#37 windowがundefinedになる問題を解消
  components/BackButton.tsx
  components/ConfirmButton.tsx
  yarn.lock
Labels: Problem: bug, Type: improvement

#38 さまざまなレイアウトの修正
  app/page.tsx
  components/BackButton.tsx
  components/ConfirmButton.tsx
  components/TeamChip.tsx
Labels: Type: design, Type: new feature

#40 Formsへのリンクを追加
  app/page.tsx
Labels: Type: improvement, Type: new feature
